(ns alm.steps)

(def st {270	"Prerequisites are met"
         271	"Login successful"
         272	"Input file has records. Input File Name: "
         273	"NA"
         274	"NA"
         275	"Input file occurrances are changed to"
         276     "Job Submitted successfully"
         277	"Preparation completed"
         278	"File sent to SAP server"
         279	"NA"
         280	"File available in ZLEG_INP folder: "
         281	"NA"
         282	"NA"
         283	"NA"
         284	"Selection screen displayed"
         285	"Fields are populated with values from variant"
         286	"File name and other parameters are populated and job submitted"
         287	"Job details shown"
         288	"Job successfully completed"
         289	"Mail with test results sent to ACE team"})
